<script>
    let props = $props();
</script>
<div class="">
<div class="-mt-[5px]"><span style="color:{props.color}" class="text-3xl">./Technology</span></div>
<div class="-mt-[5px]"><span class="text-subtext0 relative -top-[0.75px] -left-[1px]">├</span><span class="text-subtext0 allign-middle">─</span><span class="text-text">Fullstack</span></div>
<div class="-mt-[5px]"><span class="text-subtext0 ">│</span>&nbsp;&nbsp;<span class="text-overlay2 relative -top-[0.75px] -left-[1px]">├</span><span class="text-overlay2 allign-middle">─</span><span class="text-text">Backend</span></div>
<div class="-mt-[5px]"><span class="text-subtext0 ">│</span>&nbsp;&nbsp;<span class="text-overlay2 ">│</span>&nbsp;&nbsp;<span class="text-overlay1 relative -top-[0.75px] -left-[1px]">├</span><span class="pr-2" style="color: #fcc477">─</span><a href="https://www.cloudflare.com/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span class="text-text">Cloudflare</span><img loading="lazy" src="/ezaicons/dd63ffcb0064c4d85102b2c34c400dc5.svg" class="w-4 h-4" alt="Cloudflare icon" /></a></div>
<div class="-mt-[5px]"><span class="text-subtext0 ">│</span>&nbsp;&nbsp;<span class="text-overlay2 ">│</span>&nbsp;&nbsp;<span class="text-overlay1 relative -top-[0.75px] -left-[1px]">├</span><span class="pr-2" style="color: #feb675">─</span><a href="https://www.java.com/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span class="text-text">Java</span><img loading="lazy" src="/ezaicons/24cb2ea81471639978474873a6977e53.svg" class="w-4 h-4" alt="Java icon" /></a></div>
<div class="-mt-[5px]"><span class="text-subtext0 ">│</span>&nbsp;&nbsp;<span class="text-overlay2 ">│</span>&nbsp;&nbsp;<span class="text-overlay1 relative -top-[0.75px] -left-[1px]">├</span><span class="pr-2" style="color: #a2d49f">─</span><a href="https://www.mongodb.com/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span class="text-text">MongoDB</span><img loading="lazy" src="/ezaicons/6b39fbd36301f3621a36e0fed1dea4bd.svg" class="w-4 h-4" alt="MongoDB icon" /></a></div>
<div class="-mt-[5px]"><span class="text-subtext0 ">│</span>&nbsp;&nbsp;<span class="text-overlay2 ">│</span>&nbsp;&nbsp;<span class="text-overlay1 relative -top-[0.75px] -left-[1px]">├</span><span class="pr-2" style="color: #74d5ff">─</span><a href="https://www.mysql.com/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span class="text-text">MySQL</span><img loading="lazy" src="/ezaicons/916d4b008577b1f061ddce440afd716d.svg" class="w-4 h-4" alt="MySQL icon" /></a></div>
<div class="-mt-[5px]"><span class="text-subtext0 ">│</span>&nbsp;&nbsp;<span class="text-overlay2 ">│</span>&nbsp;&nbsp;<span class="text-overlay1 relative -top-[0.75px] -left-[1px]">├</span><span class="pr-2" style="color: #a7d59e">─</span><a href="https://nodejs.org/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span class="text-text">Node.js</span><img loading="lazy" src="/ezaicons/214a6d8d59d0e2e203831e8a55c1fbec.svg" class="w-4 h-4" alt="Node.js icon" /></a></div>
<div class="-mt-[5px]"><span class="text-subtext0 ">│</span>&nbsp;&nbsp;<span class="text-overlay2 ">│</span>&nbsp;&nbsp;<span class="text-overlay1 relative -top-[0.75px] -left-[1px]">├</span><span class="pr-2" style="color: #98bddb">─</span><a href="https://www.postgresql.org/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span class="text-text">Postgres</span><img loading="lazy" src="/ezaicons/9b9fda17baac9216a5034cd53544ff6d.svg" class="w-4 h-4" alt="Postgres icon" /></a></div>
<div class="-mt-[5px]"><span class="text-subtext0 ">│</span>&nbsp;&nbsp;<span class="text-overlay2 ">│</span>&nbsp;&nbsp;<span class="text-overlay1 relative -top-[0.75px] -left-[1px]">├</span><span class="pr-2" style="color: #ffe574">─</span><a href="https://www.python.org/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span class="text-text">Python</span><img loading="lazy" src="/ezaicons/2bdca420e29c3fecb2f09a12896eec63.svg" class="w-4 h-4" alt="Python icon" /></a></div>
<div class="-mt-[5px]"><span class="text-subtext0 ">│</span>&nbsp;&nbsp;<span class="text-overlay2 ">│</span>&nbsp;&nbsp;<span class="text-overlay1 relative -top-[0.75px] -left-[1px]">└</span><span class="pr-2" style="color: #f8837b">─</span><a href="https://rubyonrails.org/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span class="text-text">Ruby on Rails</span><img loading="lazy" src="/ezaicons/c0bef408c97bbb9ec0721d958ada1624.svg" class="w-4 h-4" alt="Ruby on Rails icon" /></a></div>
<div class="-mt-[5px]"><span class="text-subtext0 ">│</span>&nbsp;&nbsp;<span class="text-overlay2 relative -top-[0.75px] -left-[1px]">├</span><span class="text-overlay2 allign-middle">─</span><span class="text-text">CI-CD</span></div>
<div class="-mt-[5px]"><span class="text-subtext0 ">│</span>&nbsp;&nbsp;<span class="text-overlay2 ">│</span>&nbsp;&nbsp;<span class="text-overlay1 relative -top-[0.75px] -left-[1px]">├</span><span class="pr-2" style="color: #7fc2f4">─</span><a href="https://www.docker.com/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span class="text-text">Docker</span><img loading="lazy" src="/ezaicons/a59efc0754a85163aeec23ceefb540f9.svg" class="w-4 h-4" alt="Docker icon" /></a></div>
<div class="-mt-[5px]"><span class="text-subtext0 ">│</span>&nbsp;&nbsp;<span class="text-overlay2 ">│</span>&nbsp;&nbsp;<span class="text-overlay1 relative -top-[0.75px] -left-[1px]">└</span><span class="pr-2" style="color: #74b5ff">─</span><a href="https://github.com/features/actions" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span class="text-text">Github Actions</span><img loading="lazy" src="/ezaicons/d50dd2c0c589fc9e2e1157a28f839760.svg" class="w-4 h-4" alt="Github Actions icon" /></a></div>
<div class="-mt-[5px]"><span class="text-subtext0 ">│</span>&nbsp;&nbsp;<span class="text-overlay2 relative -top-[0.75px] -left-[1px]">└</span><span class="text-overlay2 allign-middle">─</span><span class="text-text">Frontend</span></div>
<div class="-mt-[5px]"><span class="text-subtext0 ">│</span>&nbsp;&nbsp;&nbsp;&nbsp;<span class="text-overlay2 relative -top-[0.75px] -left-[1px]">├</span><span class="pr-2" style="color: #ee85be">─</span><a href="https://astro.build/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span class="text-text">Astro</span><img loading="lazy" src="/ezaicons/365c7a3362393dae4c5378ec913e3843.svg" class="w-4 h-4" alt="Astro icon" /></a></div>
<div class="-mt-[5px]"><span class="text-subtext0 ">│</span>&nbsp;&nbsp;&nbsp;&nbsp;<span class="text-overlay2 relative -top-[0.75px] -left-[1px]">├</span><span class="pr-2" style="color: #83c2f0">─</span><a href="https://developer.mozilla.org/en-US/docs/Web/CSS" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span class="text-text">CSS</span><img loading="lazy" src="/ezaicons/479a2eae4b26695b74cec269677e9de8.svg" class="w-4 h-4" alt="CSS icon" /></a></div>
<div class="-mt-[5px]"><span class="text-subtext0 ">│</span>&nbsp;&nbsp;&nbsp;&nbsp;<span class="text-overlay2 relative -top-[0.75px] -left-[1px]">├</span><span class="pr-2" style="color: #f6a17d">─</span><a href="https://developer.mozilla.org/en-US/docs/Web/HTML" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span class="text-text">HTML</span><img loading="lazy" src="/ezaicons/509239df43ccf813082bb85db2a244dd.svg" class="w-4 h-4" alt="HTML icon" /></a></div>
<div class="-mt-[5px]"><span class="text-subtext0 ">│</span>&nbsp;&nbsp;&nbsp;&nbsp;<span class="text-overlay2 relative -top-[0.75px] -left-[1px]">├</span><span class="pr-2" style="color: #faec79">─</span><a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span class="text-text">Javascript</span><img loading="lazy" src="/ezaicons/a99b4b8b651fe8ca5dfaa5bf9ed853a9.svg" class="w-4 h-4" alt="Javascript icon" /></a></div>
<div class="-mt-[5px]"><span class="text-subtext0 ">│</span>&nbsp;&nbsp;&nbsp;&nbsp;<span class="text-overlay2 relative -top-[0.75px] -left-[1px]">├</span><span class="pr-2" style="color: #91d6e3">─</span><a href="https://reactjs.org/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span class="text-text">React</span><img loading="lazy" src="/ezaicons/98e072206420f7230df306c0cd486b7c.svg" class="w-4 h-4" alt="React icon" /></a></div>
<div class="-mt-[5px]"><span class="text-subtext0 ">│</span>&nbsp;&nbsp;&nbsp;&nbsp;<span class="text-overlay2 relative -top-[0.75px] -left-[1px]">├</span><span class="pr-2" style="color: #f9ab7a">─</span><a href="https://svelte.dev/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span class="text-text">Svelte</span><img loading="lazy" src="/ezaicons/42b604707d5895867a76f8016a49146b.svg" class="w-4 h-4" alt="Svelte icon" /></a></div>
<div class="-mt-[5px]"><span class="text-subtext0 ">│</span>&nbsp;&nbsp;&nbsp;&nbsp;<span class="text-overlay2 relative -top-[0.75px] -left-[1px]">└</span><span class="pr-2" style="color: #74daff">─</span><a href="https://tailwindcss.com/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span class="text-text">Tailwind</span><img loading="lazy" src="/ezaicons/c3f585c78a349bfce3bb19878c4d16eb.svg" class="w-4 h-4" alt="Tailwind icon" /></a></div>
<div class="-mt-[5px]"><span class="text-subtext0 relative -top-[0.75px] -left-[1px]">├</span><span class="text-subtext0 allign-middle">─</span><span class="text-text">Homelab</span></div>
<div class="-mt-[5px]"><span class="text-subtext0 ">│</span>&nbsp;&nbsp;<span class="text-overlay2 relative -top-[0.75px] -left-[1px]">├</span><span class="pr-2" style="color: #fcc477">─</span><a href="https://www.cloudflare.com/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span class="text-text">Cloudflare</span><img loading="lazy" src="/ezaicons/dd63ffcb0064c4d85102b2c34c400dc5.svg" class="w-4 h-4" alt="Cloudflare icon" /></a></div>
<div class="-mt-[5px]"><span class="text-subtext0 ">│</span>&nbsp;&nbsp;<span class="text-overlay2 relative -top-[0.75px] -left-[1px]">├</span><span class="pr-2" style="color: #ff749c">─</span><a href="https://www.debian.org/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span class="text-text">Debian</span><img loading="lazy" src="/ezaicons/184b82c31bd61f8316cd7fc116a21044.svg" class="w-4 h-4" alt="Debian icon" /></a></div>
<div class="-mt-[5px]"><span class="text-subtext0 ">│</span>&nbsp;&nbsp;<span class="text-overlay2 relative -top-[0.75px] -left-[1px]">├</span><span class="pr-2" style="color: #7fc2f4">─</span><a href="https://www.docker.com/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span class="text-text">Docker</span><img loading="lazy" src="/ezaicons/a59efc0754a85163aeec23ceefb540f9.svg" class="w-4 h-4" alt="Docker icon" /></a></div>
<div class="-mt-[5px]"><span class="text-subtext0 ">│</span>&nbsp;&nbsp;<span class="text-overlay2 relative -top-[0.75px] -left-[1px]">├</span><span class="pr-2" style="color: #e29191">─</span><a href="https://www.linux.org/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span class="text-text">Linux</span><img loading="lazy" src="/ezaicons/1f9d360f3cbd20ae99e69cefd37e1e7f.svg" class="w-4 h-4" alt="Linux icon" /></a></div>
<div class="-mt-[5px]"><span class="text-subtext0 ">│</span>&nbsp;&nbsp;<span class="text-overlay2 relative -top-[0.75px] -left-[1px]">├</span><span class="pr-2" style="color: #98aedb">─</span><a href="https://nixos.org/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span class="text-text">NixOS</span><img loading="lazy" src="/ezaicons/9a7ecf5a1f2ce73973818feebcc996e8.svg" class="w-4 h-4" alt="NixOS icon" /></a></div>
<div class="-mt-[5px]"><span class="text-subtext0 ">│</span>&nbsp;&nbsp;<span class="text-overlay2 relative -top-[0.75px] -left-[1px]">├</span><span class="pr-2" style="color: #e29491">─</span><a href="https://www.raspberrypi.com/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span class="text-text">Raspberry PI</span><img loading="lazy" src="/ezaicons/b36ca99c9f1c8164a4056fb9ae7987ca.svg" class="w-4 h-4" alt="Raspberry PI icon" /></a></div>
<div class="-mt-[5px]"><span class="text-subtext0 ">│</span>&nbsp;&nbsp;<span class="text-overlay2 relative -top-[0.75px] -left-[1px]">├</span><span class="pr-2" style="color: #c6baad">─</span><a href="https://tailscale.com/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span class="text-text">Tailscale</span><img loading="lazy" src="/ezaicons/b4d9c77b08ada78e173752f8417451d7.svg" class="w-4 h-4" alt="Tailscale icon" /></a></div>
<div class="-mt-[5px]"><span class="text-subtext0 ">│</span>&nbsp;&nbsp;<span class="text-overlay2 relative -top-[0.75px] -left-[1px]">└</span><span class="pr-2" style="color: #f29e81">─</span><a href="https://ubuntu.com/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span class="text-text">Ubuntu</span><img loading="lazy" src="/ezaicons/6e8e8362c54d5c45bc713f93c55c7897.svg" class="w-4 h-4" alt="Ubuntu icon" /></a></div>
<div class="-mt-[5px]"><span class="text-subtext0 relative -top-[0.75px] -left-[1px]">└</span><span class="text-subtext0 allign-middle">─</span><span class="text-text">Tools</span></div>
<div class="-mt-[5px]">&nbsp;&nbsp;<span class="text-subtext0 relative -top-[0.75px] -left-[1px]">├</span><span class="pr-2" style="color: #f8ac7b">─</span><a href="https://www.blender.org/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span class="text-text">Blender</span><img loading="lazy" src="/ezaicons/a5a1a221e280aa11fbb2507611ef4658.svg" class="w-4 h-4" alt="Blender icon" /></a></div>
<div class="-mt-[5px]">&nbsp;&nbsp;<span class="text-subtext0 relative -top-[0.75px] -left-[1px]">├</span><span class="pr-2" style="color: #f57eac">─</span><a href="https://www.mozilla.org/en-US/firefox/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span class="text-text">Firefox</span><img loading="lazy" src="/ezaicons/aa555575143b87b68b3f0731cc8e2793.svg" class="w-4 h-4" alt="Firefox icon" /></a></div>
<div class="-mt-[5px]">&nbsp;&nbsp;<span class="text-subtext0 relative -top-[0.75px] -left-[1px]">├</span><span class="pr-2" style="color: #80a6f3">─</span><a href="https://nixos.org/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span class="text-text">I use NixOS btw</span><img loading="lazy" src="/ezaicons/71faf3d6fdd83076fdc8831552a2812f.svg" class="w-4 h-4" alt="I use NixOS btw icon" /></a></div>
<div class="-mt-[5px]">&nbsp;&nbsp;<span class="text-subtext0 relative -top-[0.75px] -left-[1px]">├</span><span class="pr-2" style="color: #ab8de6">─</span><a href="https://obsidian.md/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span class="text-text">Obsidian</span><img loading="lazy" src="/ezaicons/4bbd420b23f392f25e43c2618a07c7c2.svg" class="w-4 h-4" alt="Obsidian icon" /></a></div>
<div class="-mt-[5px]">&nbsp;&nbsp;<span class="text-subtext0 relative -top-[0.75px] -left-[1px]">├</span><span class="pr-2" style="color: #7dc6f6">─</span><a href="https://code.visualstudio.com/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span class="text-text">VSCode</span><img loading="lazy" src="/ezaicons/e151b7d17805040cc9771fd30569b10b.svg" class="w-4 h-4" alt="VSCode icon" /></a></div>
<div class="-mt-[5px]">&nbsp;&nbsp;<span class="text-subtext0 relative -top-[0.75px] -left-[1px]">└</span><span class="pr-2" style="color: #f8907b">─</span><a href="https://zen-browser.app/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span class="text-text">Zen Browser</span><img loading="lazy" src="/ezaicons/cbc44b341642433d505cd7b1ff35ebb8.svg" class="w-4 h-4" alt="Zen Browser icon" /></a></div>
</div>