<script>
    let props = $props();
</script>
<div class="">
<div class="-mt-[5px]"><span style="color:{props.color}" class="text-3xl">./Technology</span></div>
<div class="-mt-[5px]"><span class="text-red relative -top-[0.75px] -left-[1px]">├</span><span class="text-red allign-middle">─</span><span class="text-red">Fullstack</span></div>
<div class="-mt-[5px]"><span class="text-red ">│</span>&nbsp;&nbsp;<span class="text-peach relative -top-[0.75px] -left-[1px]">├</span><span class="text-peach allign-middle">─</span><span class="text-peach">Backend</span></div>
<div class="-mt-[5px]"><span class="text-red ">│</span>&nbsp;&nbsp;<span class="text-peach ">│</span>&nbsp;&nbsp;<span class="text-yellow relative -top-[0.75px] -left-[1px]">├</span><span class="pr-2" style="color: #fddaa9">─</span><a href="https://www.cloudflare.com/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span style="color: #fddaa9" >Cloudflare</span><img loading="lazy" src="/ezaicons/dd63ffcb0064c4d85102b2c34c400dc5.svg" class="w-4 h-4" alt="Cloudflare icon" /></a></div>
<div class="-mt-[5px]"><span class="text-red ">│</span>&nbsp;&nbsp;<span class="text-peach ">│</span>&nbsp;&nbsp;<span class="text-yellow relative -top-[0.75px] -left-[1px]">├</span><span class="pr-2" style="color: #fed1a8">─</span><a href="https://www.java.com/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span style="color: #fed1a8" >Java</span><img loading="lazy" src="/ezaicons/24cb2ea81471639978474873a6977e53.svg" class="w-4 h-4" alt="Java icon" /></a></div>
<div class="-mt-[5px]"><span class="text-red ">│</span>&nbsp;&nbsp;<span class="text-peach ">│</span>&nbsp;&nbsp;<span class="text-yellow relative -top-[0.75px] -left-[1px]">├</span><span class="pr-2" style="color: #c4e3c3">─</span><a href="https://www.mongodb.com/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span style="color: #c4e3c3" >MongoDB</span><img loading="lazy" src="/ezaicons/6b39fbd36301f3621a36e0fed1dea4bd.svg" class="w-4 h-4" alt="MongoDB icon" /></a></div>
<div class="-mt-[5px]"><span class="text-red ">│</span>&nbsp;&nbsp;<span class="text-peach ">│</span>&nbsp;&nbsp;<span class="text-yellow relative -top-[0.75px] -left-[1px]">├</span><span class="pr-2" style="color: #a7e5ff">─</span><a href="https://www.mysql.com/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span style="color: #a7e5ff" >MySQL</span><img loading="lazy" src="/ezaicons/916d4b008577b1f061ddce440afd716d.svg" class="w-4 h-4" alt="MySQL icon" /></a></div>
<div class="-mt-[5px]"><span class="text-red ">│</span>&nbsp;&nbsp;<span class="text-peach ">│</span>&nbsp;&nbsp;<span class="text-yellow relative -top-[0.75px] -left-[1px]">├</span><span class="pr-2" style="color: #c8e5c1">─</span><a href="https://nodejs.org/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span style="color: #c8e5c1" >Node.js</span><img loading="lazy" src="/ezaicons/214a6d8d59d0e2e203831e8a55c1fbec.svg" class="w-4 h-4" alt="Node.js icon" /></a></div>
<div class="-mt-[5px]"><span class="text-red ">│</span>&nbsp;&nbsp;<span class="text-peach ">│</span>&nbsp;&nbsp;<span class="text-yellow relative -top-[0.75px] -left-[1px]">├</span><span class="pr-2" style="color: #bed5e8">─</span><a href="https://www.postgresql.org/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span style="color: #bed5e8" >Postgres</span><img loading="lazy" src="/ezaicons/9b9fda17baac9216a5034cd53544ff6d.svg" class="w-4 h-4" alt="Postgres icon" /></a></div>
<div class="-mt-[5px]"><span class="text-red ">│</span>&nbsp;&nbsp;<span class="text-peach ">│</span>&nbsp;&nbsp;<span class="text-yellow relative -top-[0.75px] -left-[1px]">├</span><span class="pr-2" style="color: #ffefa7">─</span><a href="https://www.python.org/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span style="color: #ffefa7" >Python</span><img loading="lazy" src="/ezaicons/2bdca420e29c3fecb2f09a12896eec63.svg" class="w-4 h-4" alt="Python icon" /></a></div>
<div class="-mt-[5px]"><span class="text-red ">│</span>&nbsp;&nbsp;<span class="text-peach ">│</span>&nbsp;&nbsp;<span class="text-yellow relative -top-[0.75px] -left-[1px]">└</span><span class="pr-2" style="color: #fab0ac">─</span><a href="https://rubyonrails.org/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span style="color: #fab0ac" >Ruby on Rails</span><img loading="lazy" src="/ezaicons/c0bef408c97bbb9ec0721d958ada1624.svg" class="w-4 h-4" alt="Ruby on Rails icon" /></a></div>
<div class="-mt-[5px]"><span class="text-red ">│</span>&nbsp;&nbsp;<span class="text-peach relative -top-[0.75px] -left-[1px]">├</span><span class="text-peach allign-middle">─</span><span class="text-peach">CI-CD</span></div>
<div class="-mt-[5px]"><span class="text-red ">│</span>&nbsp;&nbsp;<span class="text-peach ">│</span>&nbsp;&nbsp;<span class="text-yellow relative -top-[0.75px] -left-[1px]">├</span><span class="pr-2" style="color: #aed8f8">─</span><a href="https://www.docker.com/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span style="color: #aed8f8" >Docker</span><img loading="lazy" src="/ezaicons/a59efc0754a85163aeec23ceefb540f9.svg" class="w-4 h-4" alt="Docker icon" /></a></div>
<div class="-mt-[5px]"><span class="text-red ">│</span>&nbsp;&nbsp;<span class="text-peach ">│</span>&nbsp;&nbsp;<span class="text-yellow relative -top-[0.75px] -left-[1px]">└</span><span class="pr-2" style="color: #a7d0ff">─</span><a href="https://github.com/features/actions" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span style="color: #a7d0ff" >Github Actions</span><img loading="lazy" src="/ezaicons/d50dd2c0c589fc9e2e1157a28f839760.svg" class="w-4 h-4" alt="Github Actions icon" /></a></div>
<div class="-mt-[5px]"><span class="text-red ">│</span>&nbsp;&nbsp;<span class="text-peach relative -top-[0.75px] -left-[1px]">└</span><span class="text-peach allign-middle">─</span><span class="text-peach">Frontend</span></div>
<div class="-mt-[5px]"><span class="text-red ">│</span>&nbsp;&nbsp;&nbsp;&nbsp;<span class="text-peach relative -top-[0.75px] -left-[1px]">├</span><span class="pr-2" style="color: #f4b2d6">─</span><a href="https://astro.build/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span style="color: #f4b2d6" >Astro</span><img loading="lazy" src="/ezaicons/365c7a3362393dae4c5378ec913e3843.svg" class="w-4 h-4" alt="Astro icon" /></a></div>
<div class="-mt-[5px]"><span class="text-red ">│</span>&nbsp;&nbsp;&nbsp;&nbsp;<span class="text-peach relative -top-[0.75px] -left-[1px]">├</span><span class="pr-2" style="color: #b1d8f5">─</span><a href="https://developer.mozilla.org/en-US/docs/Web/CSS" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span style="color: #b1d8f5" >CSS</span><img loading="lazy" src="/ezaicons/479a2eae4b26695b74cec269677e9de8.svg" class="w-4 h-4" alt="CSS icon" /></a></div>
<div class="-mt-[5px]"><span class="text-red ">│</span>&nbsp;&nbsp;&nbsp;&nbsp;<span class="text-peach relative -top-[0.75px] -left-[1px]">├</span><span class="pr-2" style="color: #f9c4ad">─</span><a href="https://developer.mozilla.org/en-US/docs/Web/HTML" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span style="color: #f9c4ad" >HTML</span><img loading="lazy" src="/ezaicons/509239df43ccf813082bb85db2a244dd.svg" class="w-4 h-4" alt="HTML icon" /></a></div>
<div class="-mt-[5px]"><span class="text-red ">│</span>&nbsp;&nbsp;&nbsp;&nbsp;<span class="text-peach relative -top-[0.75px] -left-[1px]">├</span><span class="pr-2" style="color: #fcf3aa">─</span><a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span style="color: #fcf3aa" >Javascript</span><img loading="lazy" src="/ezaicons/a99b4b8b651fe8ca5dfaa5bf9ed853a9.svg" class="w-4 h-4" alt="Javascript icon" /></a></div>
<div class="-mt-[5px]"><span class="text-red ">│</span>&nbsp;&nbsp;&nbsp;&nbsp;<span class="text-peach relative -top-[0.75px] -left-[1px]">├</span><span class="pr-2" style="color: #b9e5ed">─</span><a href="https://reactjs.org/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span style="color: #b9e5ed" >React</span><img loading="lazy" src="/ezaicons/98e072206420f7230df306c0cd486b7c.svg" class="w-4 h-4" alt="React icon" /></a></div>
<div class="-mt-[5px]"><span class="text-red ">│</span>&nbsp;&nbsp;&nbsp;&nbsp;<span class="text-peach relative -top-[0.75px] -left-[1px]">├</span><span class="pr-2" style="color: #fbcaab">─</span><a href="https://svelte.dev/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span style="color: #fbcaab" >Svelte</span><img loading="lazy" src="/ezaicons/42b604707d5895867a76f8016a49146b.svg" class="w-4 h-4" alt="Svelte icon" /></a></div>
<div class="-mt-[5px]"><span class="text-red ">│</span>&nbsp;&nbsp;&nbsp;&nbsp;<span class="text-peach relative -top-[0.75px] -left-[1px]">└</span><span class="pr-2" style="color: #a7e8ff">─</span><a href="https://tailwindcss.com/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span style="color: #a7e8ff" >Tailwind</span><img loading="lazy" src="/ezaicons/c3f585c78a349bfce3bb19878c4d16eb.svg" class="w-4 h-4" alt="Tailwind icon" /></a></div>
<div class="-mt-[5px]"><span class="text-red relative -top-[0.75px] -left-[1px]">├</span><span class="text-red allign-middle">─</span><span class="text-red">Homelab</span></div>
<div class="-mt-[5px]"><span class="text-red ">│</span>&nbsp;&nbsp;<span class="text-peach relative -top-[0.75px] -left-[1px]">├</span><span class="pr-2" style="color: #fddaa9">─</span><a href="https://www.cloudflare.com/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span style="color: #fddaa9" >Cloudflare</span><img loading="lazy" src="/ezaicons/dd63ffcb0064c4d85102b2c34c400dc5.svg" class="w-4 h-4" alt="Cloudflare icon" /></a></div>
<div class="-mt-[5px]"><span class="text-red ">│</span>&nbsp;&nbsp;<span class="text-peach relative -top-[0.75px] -left-[1px]">├</span><span class="pr-2" style="color: #ffa7c0">─</span><a href="https://www.debian.org/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span style="color: #ffa7c0" >Debian</span><img loading="lazy" src="/ezaicons/184b82c31bd61f8316cd7fc116a21044.svg" class="w-4 h-4" alt="Debian icon" /></a></div>
<div class="-mt-[5px]"><span class="text-red ">│</span>&nbsp;&nbsp;<span class="text-peach relative -top-[0.75px] -left-[1px]">├</span><span class="pr-2" style="color: #aed8f8">─</span><a href="https://www.docker.com/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span style="color: #aed8f8" >Docker</span><img loading="lazy" src="/ezaicons/a59efc0754a85163aeec23ceefb540f9.svg" class="w-4 h-4" alt="Docker icon" /></a></div>
<div class="-mt-[5px]"><span class="text-red ">│</span>&nbsp;&nbsp;<span class="text-peach relative -top-[0.75px] -left-[1px]">├</span><span class="pr-2" style="color: #ecbaba">─</span><a href="https://www.linux.org/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span style="color: #ecbaba" >Linux</span><img loading="lazy" src="/ezaicons/1f9d360f3cbd20ae99e69cefd37e1e7f.svg" class="w-4 h-4" alt="Linux icon" /></a></div>
<div class="-mt-[5px]"><span class="text-red ">│</span>&nbsp;&nbsp;<span class="text-peach relative -top-[0.75px] -left-[1px]">├</span><span class="pr-2" style="color: #becce8">─</span><a href="https://nixos.org/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span style="color: #becce8" >NixOS</span><img loading="lazy" src="/ezaicons/9a7ecf5a1f2ce73973818feebcc996e8.svg" class="w-4 h-4" alt="NixOS icon" /></a></div>
<div class="-mt-[5px]"><span class="text-red ">│</span>&nbsp;&nbsp;<span class="text-peach relative -top-[0.75px] -left-[1px]">├</span><span class="pr-2" style="color: #edbcb9">─</span><a href="https://www.raspberrypi.com/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span style="color: #edbcb9" >Raspberry PI</span><img loading="lazy" src="/ezaicons/b36ca99c9f1c8164a4056fb9ae7987ca.svg" class="w-4 h-4" alt="Raspberry PI icon" /></a></div>
<div class="-mt-[5px]"><span class="text-red ">│</span>&nbsp;&nbsp;<span class="text-peach relative -top-[0.75px] -left-[1px]">├</span><span class="pr-2" style="color: #dbd3cb">─</span><a href="https://tailscale.com/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span style="color: #dbd3cb" >Tailscale</span><img loading="lazy" src="/ezaicons/b4d9c77b08ada78e173752f8417451d7.svg" class="w-4 h-4" alt="Tailscale icon" /></a></div>
<div class="-mt-[5px]"><span class="text-red ">│</span>&nbsp;&nbsp;<span class="text-peach relative -top-[0.75px] -left-[1px]">└</span><span class="pr-2" style="color: #f7c2af">─</span><a href="https://ubuntu.com/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span style="color: #f7c2af" >Ubuntu</span><img loading="lazy" src="/ezaicons/6e8e8362c54d5c45bc713f93c55c7897.svg" class="w-4 h-4" alt="Ubuntu icon" /></a></div>
<div class="-mt-[5px]"><span class="text-red relative -top-[0.75px] -left-[1px]">└</span><span class="text-red allign-middle">─</span><span class="text-red">Tools</span></div>
<div class="-mt-[5px]">&nbsp;&nbsp;<span class="text-red relative -top-[0.75px] -left-[1px]">├</span><span class="pr-2" style="color: #facaac">─</span><a href="https://www.blender.org/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span style="color: #facaac" >Blender</span><img loading="lazy" src="/ezaicons/a5a1a221e280aa11fbb2507611ef4658.svg" class="w-4 h-4" alt="Blender icon" /></a></div>
<div class="-mt-[5px]">&nbsp;&nbsp;<span class="text-red relative -top-[0.75px] -left-[1px]">├</span><span class="pr-2" style="color: #f9adcb">─</span><a href="https://www.mozilla.org/en-US/firefox/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span style="color: #f9adcb" >Firefox</span><img loading="lazy" src="/ezaicons/aa555575143b87b68b3f0731cc8e2793.svg" class="w-4 h-4" alt="Firefox icon" /></a></div>
<div class="-mt-[5px]">&nbsp;&nbsp;<span class="text-red relative -top-[0.75px] -left-[1px]">├</span><span class="pr-2" style="color: #afc7f7">─</span><a href="https://nixos.org/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span style="color: #afc7f7" >I use NixOS btw</span><img loading="lazy" src="/ezaicons/71faf3d6fdd83076fdc8831552a2812f.svg" class="w-4 h-4" alt="I use NixOS btw icon" /></a></div>
<div class="-mt-[5px]">&nbsp;&nbsp;<span class="text-red relative -top-[0.75px] -left-[1px]">├</span><span class="pr-2" style="color: #cab7ef">─</span><a href="https://obsidian.md/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span style="color: #cab7ef" >Obsidian</span><img loading="lazy" src="/ezaicons/4bbd420b23f392f25e43c2618a07c7c2.svg" class="w-4 h-4" alt="Obsidian icon" /></a></div>
<div class="-mt-[5px]">&nbsp;&nbsp;<span class="text-red relative -top-[0.75px] -left-[1px]">├</span><span class="pr-2" style="color: #addbf9">─</span><a href="https://code.visualstudio.com/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span style="color: #addbf9" >VSCode</span><img loading="lazy" src="/ezaicons/e151b7d17805040cc9771fd30569b10b.svg" class="w-4 h-4" alt="VSCode icon" /></a></div>
<div class="-mt-[5px]">&nbsp;&nbsp;<span class="text-red relative -top-[0.75px] -left-[1px]">└</span><span class="pr-2" style="color: #fbb9ab">─</span><a href="https://zen-browser.app/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span style="color: #fbb9ab" >Zen Browser</span><img loading="lazy" src="/ezaicons/cbc44b341642433d505cd7b1ff35ebb8.svg" class="w-4 h-4" alt="Zen Browser icon" /></a></div>
</div>