<div class="grid grid-cols-1 -gap-5">
<p class="-mt-[6px]"><span class="text-red">./Technology</span></p>
<p class="-mt-[6px]"><span class="text-red">├</span><span class="text-peach">── Fullstack</span></p>
<p class="-mt-[6px]"><span class="text-red">│</span>&nbsp;&nbsp;&nbsp;<span class="text-peach">├</span><span class="text-yellow">── Backend</span></p>
<p class="-mt-[6px]"><span class="text-red">│</span>&nbsp;&nbsp;&nbsp;<span class="text-peach">│</span>&nbsp;&nbsp;&nbsp;<span class="text-yellow">├</span><span class="pr-2" style="color: #FBAD41">──</span><a href="https://www.cloudflare.com/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span style="color: #FBAD41">Cloudflare</span><img src="/ezaicons/dd63ffcb0064c4d85102b2c34c400dc5.svg" class="w-4 h-4" alt="Cloudflare icon" /></a></p>
<p class="-mt-[6px]"><span class="text-red">│</span>&nbsp;&nbsp;&nbsp;<span class="text-peach">│</span>&nbsp;&nbsp;&nbsp;<span class="text-yellow">├</span><span class="pr-2" style="color: #E16C01">──</span><a href="https://www.java.com/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span style="color: #E16C01">Java</span><img src="/ezaicons/24cb2ea81471639978474873a6977e53.svg" class="w-4 h-4" alt="Java icon" /></a></p>
<p class="-mt-[6px]"><span class="text-red">│</span>&nbsp;&nbsp;&nbsp;<span class="text-peach">│</span>&nbsp;&nbsp;&nbsp;<span class="text-yellow">├</span><span class="pr-2" style="color: #52AB4D">──</span><a href="https://www.mongodb.com/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span style="color: #52AB4D">MongoDB</span><img src="/ezaicons/6b39fbd36301f3621a36e0fed1dea4bd.svg" class="w-4 h-4" alt="MongoDB icon" /></a></p>
<p class="-mt-[6px]"><span class="text-red">│</span>&nbsp;&nbsp;&nbsp;<span class="text-peach">│</span>&nbsp;&nbsp;&nbsp;<span class="text-yellow">├</span><span class="pr-2" style="color: #00618A">──</span><a href="https://www.mysql.com/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span style="color: #00618A">MySQL</span><img src="/ezaicons/916d4b008577b1f061ddce440afd716d.svg" class="w-4 h-4" alt="MySQL icon" /></a></p>
<p class="-mt-[6px]"><span class="text-red">│</span>&nbsp;&nbsp;&nbsp;<span class="text-peach">│</span>&nbsp;&nbsp;&nbsp;<span class="text-yellow">├</span><span class="pr-2" style="color: #539E43">──</span><a href="https://nodejs.org/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span style="color: #539E43">Node.js</span><img src="/ezaicons/214a6d8d59d0e2e203831e8a55c1fbec.svg" class="w-4 h-4" alt="Node.js icon" /></a></p>
<p class="-mt-[6px]"><span class="text-red">│</span>&nbsp;&nbsp;&nbsp;<span class="text-peach">│</span>&nbsp;&nbsp;&nbsp;<span class="text-yellow">├</span><span class="pr-2" style="color: #336791">──</span><a href="https://www.postgresql.org/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span style="color: #336791">Postgres</span><img src="/ezaicons/9b9fda17baac9216a5034cd53544ff6d.svg" class="w-4 h-4" alt="Postgres icon" /></a></p>
<p class="-mt-[6px]"><span class="text-red">│</span>&nbsp;&nbsp;&nbsp;<span class="text-peach">│</span>&nbsp;&nbsp;&nbsp;<span class="text-yellow">├</span><span class="pr-2" style="color: #FFE365">──</span><a href="https://www.python.org/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span style="color: #FFE365">Python</span><img src="/ezaicons/2bdca420e29c3fecb2f09a12896eec63.svg" class="w-4 h-4" alt="Python icon" /></a></p>
<p class="-mt-[6px]"><span class="text-red">│</span>&nbsp;&nbsp;&nbsp;<span class="text-peach">│</span>&nbsp;&nbsp;&nbsp;<span class="text-yellow">└</span><span class="pr-2" style="color: #8A0F07">──</span><a href="https://rubyonrails.org/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span style="color: #8A0F07">Ruby on Rails</span><img src="/ezaicons/c0bef408c97bbb9ec0721d958ada1624.svg" class="w-4 h-4" alt="Ruby on Rails icon" /></a></p>
<p class="-mt-[6px]"><span class="text-red">│</span>&nbsp;&nbsp;&nbsp;<span class="text-peach">├</span><span class="text-yellow">── CI-CD</span></p>
<p class="-mt-[6px]"><span class="text-red">│</span>&nbsp;&nbsp;&nbsp;<span class="text-peach">│</span>&nbsp;&nbsp;&nbsp;<span class="text-yellow">├</span><span class="pr-2" style="color: #2396ED">──</span><a href="https://www.docker.com/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span style="color: #2396ED">Docker</span><img src="/ezaicons/a59efc0754a85163aeec23ceefb540f9.svg" class="w-4 h-4" alt="Docker icon" /></a></p>
<p class="-mt-[6px]"><span class="text-red">│</span>&nbsp;&nbsp;&nbsp;<span class="text-peach">│</span>&nbsp;&nbsp;&nbsp;<span class="text-yellow">└</span><span class="pr-2" style="color: #79B8FF">──</span><a href="https://github.com/features/actions" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span style="color: #79B8FF">Github Actions</span><img src="/ezaicons/d50dd2c0c589fc9e2e1157a28f839760.svg" class="w-4 h-4" alt="Github Actions icon" /></a></p>
<p class="-mt-[6px]"><span class="text-red">│</span>&nbsp;&nbsp;&nbsp;<span class="text-peach">└</span><span class="text-yellow">── Frontend</span></p>
<p class="-mt-[6px]"><span class="text-red">│</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="text-peach">├</span><span class="pr-2" style="color: #E43A96">──</span><a href="https://astro.build/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span style="color: #E43A96">Astro</span><img src="/ezaicons/365c7a3362393dae4c5378ec913e3843.svg" class="w-4 h-4" alt="Astro icon" /></a></p>
<p class="-mt-[6px]"><span class="text-red">│</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="text-peach">├</span><span class="pr-2" style="color: #1572B6">──</span><a href="https://developer.mozilla.org/en-US/docs/Web/CSS" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span style="color: #1572B6">CSS</span><img src="/ezaicons/479a2eae4b26695b74cec269677e9de8.svg" class="w-4 h-4" alt="CSS icon" /></a></p>
<p class="-mt-[6px]"><span class="text-red">│</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="text-peach">├</span><span class="pr-2" style="color: #F1662A">──</span><a href="https://developer.mozilla.org/en-US/docs/Web/HTML" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span style="color: #F1662A">HTML</span><img src="/ezaicons/509239df43ccf813082bb85db2a244dd.svg" class="w-4 h-4" alt="HTML icon" /></a></p>
<p class="-mt-[6px]"><span class="text-red">│</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="text-peach">├</span><span class="pr-2" style="color: #F7DF1E">──</span><a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span style="color: #F7DF1E">Javascript</span><img src="/ezaicons/a99b4b8b651fe8ca5dfaa5bf9ed853a9.svg" class="w-4 h-4" alt="Javascript icon" /></a></p>
<p class="-mt-[6px]"><span class="text-red">│</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="text-peach">├</span><span class="pr-2" style="color: #91D7E3">──</span><a href="https://reactjs.org/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span style="color: #91D7E3">React</span><img src="/ezaicons/98e072206420f7230df306c0cd486b7c.svg" class="w-4 h-4" alt="React icon" /></a></p>
<p class="-mt-[6px]"><span class="text-red">│</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="text-peach">├</span><span class="pr-2" style="color: #FAB387">──</span><a href="https://svelte.dev/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span style="color: #FAB387">Svelte</span><img src="/ezaicons/42b604707d5895867a76f8016a49146b.svg" class="w-4 h-4" alt="Svelte icon" /></a></p>
<p class="-mt-[6px]"><span class="text-red">│</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="text-peach">└</span><span class="pr-2" style="color: #00BCFF">──</span><a href="https://tailwindcss.com/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span style="color: #00BCFF">Tailwind</span><img src="/ezaicons/c3f585c78a349bfce3bb19878c4d16eb.svg" class="w-4 h-4" alt="Tailwind icon" /></a></p>
<p class="-mt-[6px]"><span class="text-red">├</span><span class="text-peach">── Homelab</span></p>
<p class="-mt-[6px]"><span class="text-red">│</span>&nbsp;&nbsp;&nbsp;<span class="text-peach">├</span><span class="pr-2" style="color: #FBAD41">──</span><a href="https://www.cloudflare.com/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span style="color: #FBAD41">Cloudflare</span><img src="/ezaicons/dd63ffcb0064c4d85102b2c34c400dc5.svg" class="w-4 h-4" alt="Cloudflare icon" /></a></p>
<p class="-mt-[6px]"><span class="text-red">│</span>&nbsp;&nbsp;&nbsp;<span class="text-peach">├</span><span class="pr-2" style="color: #A80030">──</span><a href="https://www.debian.org/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span style="color: #A80030">Debian</span><img src="/ezaicons/184b82c31bd61f8316cd7fc116a21044.svg" class="w-4 h-4" alt="Debian icon" /></a></p>
<p class="-mt-[6px]"><span class="text-red">│</span>&nbsp;&nbsp;&nbsp;<span class="text-peach">├</span><span class="pr-2" style="color: #2396ED">──</span><a href="https://www.docker.com/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span style="color: #2396ED">Docker</span><img src="/ezaicons/a59efc0754a85163aeec23ceefb540f9.svg" class="w-4 h-4" alt="Docker icon" /></a></p>
<p class="-mt-[6px]"><span class="text-red">│</span>&nbsp;&nbsp;&nbsp;<span class="text-peach">├</span><span class="pr-2" style="color: #F0C6C6">──</span><a href="https://www.linux.org/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span style="color: #F0C6C6">Linux</span><img src="/ezaicons/1f9d360f3cbd20ae99e69cefd37e1e7f.svg" class="w-4 h-4" alt="Linux icon" /></a></p>
<p class="-mt-[6px]"><span class="text-red">│</span>&nbsp;&nbsp;&nbsp;<span class="text-peach">├</span><span class="pr-2" style="color: #5277C3">──</span><a href="https://nixos.org/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span style="color: #5277C3">NixOS</span><img src="/ezaicons/9a7ecf5a1f2ce73973818feebcc996e8.svg" class="w-4 h-4" alt="NixOS icon" /></a></p>
<p class="-mt-[6px]"><span class="text-red">│</span>&nbsp;&nbsp;&nbsp;<span class="text-peach">├</span><span class="pr-2" style="color: #C13832">──</span><a href="https://www.raspberrypi.com/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span style="color: #C13832">Raspberry PI</span><img src="/ezaicons/b36ca99c9f1c8164a4056fb9ae7987ca.svg" class="w-4 h-4" alt="Raspberry PI icon" /></a></p>
<p class="-mt-[6px]"><span class="text-red">│</span>&nbsp;&nbsp;&nbsp;<span class="text-peach">├</span><span class="pr-2" style="color: #F6F4F2">──</span><a href="https://tailscale.com/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span style="color: #F6F4F2">Tailscale</span><img src="/ezaicons/b4d9c77b08ada78e173752f8417451d7.svg" class="w-4 h-4" alt="Tailscale icon" /></a></p>
<p class="-mt-[6px]"><span class="text-red">│</span>&nbsp;&nbsp;&nbsp;<span class="text-peach">└</span><span class="pr-2" style="color: #E95420">──</span><a href="https://ubuntu.com/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span style="color: #E95420">Ubuntu</span><img src="/ezaicons/6e8e8362c54d5c45bc713f93c55c7897.svg" class="w-4 h-4" alt="Ubuntu icon" /></a></p>
<p class="-mt-[6px]"><span class="text-red">└</span><span class="text-peach">── Tools</span></p>
<p class="-mt-[6px]">&nbsp;&nbsp;&nbsp;&nbsp;<span class="text-red">├</span><span class="pr-2" style="color: #F4792B">──</span><a href="https://www.blender.org/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span style="color: #F4792B">Blender</span><img src="/ezaicons/a5a1a221e280aa11fbb2507611ef4658.svg" class="w-4 h-4" alt="Blender icon" /></a></p>
<p class="-mt-[6px]">&nbsp;&nbsp;&nbsp;&nbsp;<span class="text-red">├</span><span class="pr-2" style="color: #DC105F">──</span><a href="https://www.mozilla.org/en-US/firefox/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span style="color: #DC105F">Firefox</span><img src="/ezaicons/aa555575143b87b68b3f0731cc8e2793.svg" class="w-4 h-4" alt="Firefox icon" /></a></p>
<p class="-mt-[6px]">&nbsp;&nbsp;&nbsp;&nbsp;<span class="text-red">├</span><span class="pr-2" style="color: #8AADF4">──</span><a href="https://nixos.org/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span style="color: #8AADF4">I use NixOS btw</span><img src="/ezaicons/71faf3d6fdd83076fdc8831552a2812f.svg" class="w-4 h-4" alt="I use NixOS btw icon" /></a></p>
<p class="-mt-[6px]">&nbsp;&nbsp;&nbsp;&nbsp;<span class="text-red">├</span><span class="pr-2" style="color: #4C239F">──</span><a href="https://obsidian.md/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span style="color: #4C239F">Obsidian</span><img src="/ezaicons/4bbd420b23f392f25e43c2618a07c7c2.svg" class="w-4 h-4" alt="Obsidian icon" /></a></p>
<p class="-mt-[6px]">&nbsp;&nbsp;&nbsp;&nbsp;<span class="text-red">├</span><span class="pr-2" style="color: #4EB1F3">──</span><a href="https://code.visualstudio.com/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span style="color: #4EB1F3">VSCode</span><img src="/ezaicons/e151b7d17805040cc9771fd30569b10b.svg" class="w-4 h-4" alt="VSCode icon" /></a></p>
<p class="-mt-[6px]">&nbsp;&nbsp;&nbsp;&nbsp;<span class="text-red">└</span><span class="pr-2" style="color: #F76F53">──</span><a href="https://zen-browser.app/" class="inline-flex items-center gap-2 transition-colors duration-200 hover:brightness-125" target="_blank"><span style="color: #F76F53">Zen Browser</span><img src="/ezaicons/cbc44b341642433d505cd7b1ff35ebb8.svg" class="w-4 h-4" alt="Zen Browser icon" /></a></p>
</div>