name: ci

on:
  push:
    branches:
      - main
jobs:
  docker:
    runs-on: self-hosted
    steps:
      - name: docker auth
        run: |
          docker -H tcp://docker-in-docker:2375 login forgejo.shloklab.us -u ${{ secrets.USER }} -p "${{ secrets.PASS }}"
      -
        name: Check out the Repo
        uses: actions/checkout@v4

      - name: docker build
        run: |
            docker -H tcp://docker-in-docker:2375 build -t shlokbhakta/portfolio-site:latest .
      - name: docker push
        run: |
            docker -H tcp://docker-in-docker:2375 push shlokbhakta/portfolio-site:latest