name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Check out the Repo
        uses: actions/checkout@v4

      - name: Docker login
        run: docker login forgejo.shloklab.us -u ${{ secrets.USER }} -p "${{ secrets.PASS }}"

      - name: Docker build
        run: docker build -t ShlokBhakta/Portfolio-Site:latest .

      - name: Docker push
        run: docker push ShlokBhakta/Portfolio-Site:latest