name: ci

on:
  push:
    branches:
      - main
jobs:
  docker:
    runs-on: docker
    container:
      image: docker:27.0.3-dind-alpine3.20
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    steps:
      - 
        name: Install Docker CLI
        run: |
          apk add --update nodejs nodejs-npm
      -
        name: Login to Forgejo
        uses: docker/login-action@v3
        with:
          registry: forgejo.shloklab.us
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
      -
        name: Check out the Repo
        uses: actions/checkout@v4
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ShlokBhakta/Portfolio-Site:latest