name: ci

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-22.04
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      env:
        DOCKER_HOST: tcp://docker-in-docker:2375
    steps:
      - name: docker auth
        run: |
          docker login forgejo.shloklab.us -u ${{ secrets.USER }} -p "${{ secrets.PASS }}"
      - name: Check out the Repo
        uses: actions/checkout@v4
      - name: Build Docker image
        run: |
          docker -H tcp://docker-in-docker:2375 build -t shlokbhakta/portfolio-site:latest .
