name: ci

on:
  push:
    branches:
      - main
jobs:
  docker:
    runs-on: docker
    container:
      image: catthehacker/ubuntu:act-latest
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    steps:
      - name: Install Docker CLI
        run: |
          apt-get update
          apt-get install -y docker.io
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Forgejo
        uses: docker/login-action@v3
        with:
          registry: forgejo.shloklab.us
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ShlokBhakta/Portfolio-Site:latest