version: '3.8'

services:
  app:
    image: mcr.microsoft.com/devcontainers/javascript-node:1-20-bullseye
    volumes:
      - ../..:/workspaces:cached
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:pb
    # environment variables
    # environment:
      # DB_LOCATION: ""
    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  pb:
    image: ghcr.io/muchobien/pocketbase:latest
    hostname: pocketbase
    ports:
      - "5432:8090"
    volumes: # make directory (change left side) EX: (change:keep)
      - /home/shlok/pocketBaseWebsiteTest/data:/pb_data # Create a directory called data
      - /home/shlok/pocketBaseWebsiteTest/pub:/pb_public # Create a directory called public 
    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward pocketbase locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  cloudflared: 
    image: cloudflare/cloudflared 
    container_name: cloudflare-tunnel 
    restart: unless-stopped 
    command: tunnel run 
    environment: 
      - TUNNEL_TOKEN=${TUNNELTOKEN}