name: ci

on:
  push:
    branches:
      - main
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout Repo 
        uses: actions/checkout@v4
      - name: Get next version
        uses: reecetech/version-increment@2024.4.3
        id: version
        with:
          scheme: calver 
          increment: patch
      -
        name: Login to github
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: 
            ghcr.io/shlok-bhakta/portfolio-site:latest, ghcr.io/shlok-bhakta/portfolio-site:${{ steps.version.outputs.version }}